#!/bin/sh

install_nix() {
  # This one courtesy of:
  # https://github.com/shadowrylander/shadowrylander/blob/35bb51822c46578d0a5da5810263fa85d464043c/.config/yadm/bootstrap#L56
  install_nix_bin() {
    curl -L https://nixos.org/nix/install | sh
    if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
      . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
    fi
  }
  command -v nix >/dev/null 2>&1 || install_nix_bin

  if [ -f "$HOME/.config/nix/installed_packages" ]; then
    # This list created with `nix-env -qaPs|grep '^I'|awk '{print $2}' > ~/.config/nix/installed_packages`
    cat "$HOME/.config/nix/installed_packages" | xargs nix-env -iA
  fi
  if [ -f "$HOME/.config/nix/installed_packages.local" ]; then
    # Additional packages that might be needed here or there
    cat "$HOME/.config/nix/installed_packages.local" | xargs nix-env -i
  fi
}

configure_vim() {
  # Install vim-plug for Vim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +'PlugInstall --sync' +qa
  # Install vim-plug for Neovim
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  nvim +'PlugInstall --sync' +qa
}

configure_tmux() {
  CUR_DIR=$(pwd)
  cd ~
  ln -s -f .tmux/.tmux.conf
  cd $CUR_DIR
}

install_submodules() {
    CUR_DIR=$(pwd)
    yadm submodule update --init --recursive
    cd ~/.oh-my-zsh
    git checkout custom-submodules
    git submodule update --init --recursive
    cd $CUR_DIR
}

install_submodules

install_nix

configure_vim
configure_tmux